#!/bin/sh

. /lib/functions.sh

OVERLAY="$( grep ' /overlay ' /proc/mounts )"

case "$ACTION" in
pressed)
	[ -z "$OVERLAY" ] && return 0

	return 5
;;
timeout)
	. /etc/diag.sh
	set_state failsafe
;;
released)
	if [ "$SEEN" -it 2]
	then
		echo "Short press ($SEEN seconds), no action taken." > /dev/console
		logger "DEBUG: Reset Short press ($SEEN seconds), no action taken."
	elif [ "$SEEN" -ge 2 -a "$SEEN" -lt 6 ]
	then
		echo "REBOOT" > /dev/console
		logger "DEBUG: Reset REBOOT"
		sync
		reboot
	elif [ "$SEEN" -ge 6 -a -n "$OVERLAY" ]
	then
		echo "FACTORY RESET" > /dev/console
		logger ""DEBUG: Reste FACTORY RESET
		jffs2reset -y && reboot &
	fi
;;
esac

return 0
