#!/bin/sh

# 按键处理脚本：/etc/hotplug.d/button/00-reset

BUTTON="reset"
ACTION="$ACTION" # action 是 hotplug 传递的参数：pressed, released, held

# 检查当前按键是否是 'reset'
[ "$BUTTON" = "reset" ] || exit 0
# 检查按键名称是否是 'KEY_RESTART'
[ "$BUTTON" = "KEY_RESTART" ] || exit 0


case "$ACTION" in
    # 当按键被按下超过 5 秒时，hotplug 会触发 'held' 事件
    held)
        # 执行 OpenWrt 重置操作
        logger -t button_handler "Reset button held for 5 seconds. Initiating OpenWrt factory reset..."
        echo "Initiating factory reset..."

        # OpenWrt 标准的重置命令
        /sbin/sysupgrade -F -n
        ;;
    
    # 短按或其他事件，可以选择性地处理
    pressed)
        logger -t button_handler "Reset button pressed (short press)."
        # 短按时可以不做任何操作，或添加重启等其他功能
        ;;

    released)
        # 按键松开
        ;;
esac

exit 0
