#!/bin/sh

# Hotplug 机制会传递 BUTTON, ACTION, SEEN 等环境变量

logger "DEBUG: the button was ${BUTTON} and the action was ${ACTION}, Seen: $SEEN"

[ "${BUTTON}" = "BTN_0" ] {
	case "$ACTION" in
    		pressed) // 此时的释放可能对应了 ON 状态（极性定义与硬件不符）
        		logger "模式开关拨到 ON/Pressed : 启用 Wi-Fi"
        		# /sbin/wifi up
			uci set wireless.@wifi-device[0].disabled="0"
			uci set wireless.@wifi-device[1].disabled="0"
			wifi
        		;;
    		released) // 此时的按下可能对应了 OFF 状态（极性定义与硬件不符）
        		logger "模式开关拨到 OFF/Released : 禁用 Wi-Fi"
       			#/sbin/wifi down
        		uci set wireless.@wifi-device[0].disabled="1"
			uci set wireless.@wifi-device[1].disabled="1"
			wifi
			;;
	esac
	exit 0
}
