#!/bin/sh

logger "DEBUG: The switch was ${BUTTON} and the action was ${ACTION}"

# 假设您的 DTS 配置让驱动传递 'mode_switch' 或 'BTN_0'
if [ "${BUTTON}" = "mode_switch" ] || [ "${BUTTON}" = "BTN_0" ]; then

    case "$ACTION" in
        pressed)
            logger "模式开关拨到 UP/ON : 启用 Wi-Fi"
            
            # 设置 Wi-Fi 禁用状态为 0 (启用)
            uci set wireless.@wifi-device[0].disabled="0"
            uci set wireless.@wifi-device[1].disabled="0"
            
            # 保存配置并应用
            uci commit wireless
            wifi
        ;;
        
        released)
            logger "模式开关拨到 DOWN/OFF : 禁用 Wi-Fi"
            
            # 设置 Wi-Fi 禁用状态为 1 (禁用)
            uci set wireless.@wifi-device[0].disabled="1"
            uci set wireless.@wifi-device[1].disabled="1"
            
            # 保存配置并应用
            uci commit wireless
            wifi
        ;;
    esac
    exit 0
fi
