#!/bin/sh /etc/rc.common
# Copyright (C) 2026 Fix: changes to the saved configuration only take effect after a restart.

USE_PROCD=1
START=99

CONFIG=socat
CONFIG_PATH=/var/etc/$CONFIG

PORT_FILE="/var/etc/$CONFIG.port"

add_rule() {
	[ -s "$PORT_FILE" ] || return
	local accept_port=$(cat "$PORT_FILE" | tr "\n" " ")

	uci -q delete firewall.socat
	uci set firewall.socat=rule
	uci set firewall.socat.name="socat"
	uci set firewall.socat.target="ACCEPT"
	uci set firewall.socat.src='*'
	uci set firewall.socat.dest_port="$accept_port"
	uci set firewall.socat.enabled="1"
	uci commit firewall
	/etc/init.d/firewall reload >/dev/null 2>&1
}

run_service() {
	local s="$1"
	local enable remarks protocol family proto listen_port reuseaddr
	local dest_proto dest_ip dest_port proxy proxy_server proxy_port firewall_accept

	config_get enable "$s" enable
	[ "$enable" = "0" ] && return

	config_get protocol "$s" protocol
	config_get family "$s" family
	config_get proto "$s" proto
	config_get listen_port "$s" listen_port
	config_get reuseaddr "$s" reuseaddr
	config_get dest_proto "$s" dest_proto
	config_get dest_ip "$s" dest_ip
	config_get dest_port "$s" dest_port
	config_get proxy "$s" proxy
	config_get proxy_server "$s" proxy_server
	config_get proxy_port "$s" proxy_port
	config_get firewall_accept "$s" firewall_accept

	local instance_bin="${CONFIG_PATH}/$s"
	[ -L "$instance_bin" ] || ln -s /usr/bin/socat "$instance_bin"

	if [ "$dest_proto" = "tcp6" ] || [ "$dest_proto" = "udp6" ]; then
		dest_ip="[$dest_ip]"
	fi

	local reuseaddr_param=""
	[ "$reuseaddr" = "1" ] && reuseaddr_param=",reuseaddr"

	local ipv6only_params=""
	[ "$family" = "6" ] && ipv6only_params=",ipv6-v6only"

	if [ "$protocol" = "port_forwards" ]; then
		local listen="${proto}${family}"
		[ -z "$family" ] && listen="${proto}6"

		local proxy_arg=""
		if [ -n "$proxy" ]; then
			[ "$proxy" = "socks4/4a" ] && { dest_proto="socks4a"; proxy_arg=",socksport=${proxy_port}"; }
			[ "$proxy" = "http" ] && { dest_proto="proxy"; proxy_arg=",proxyport=${proxy_port}"; }
			[ -n "$proxy_server" ] && dest_proto="${dest_proto}:${proxy_server}"
		fi

		procd_open_instance "$s"
		procd_set_param command "$instance_bin" "${listen}-listen:${listen_port}${ipv6only_params}${reuseaddr_param},fork" "${dest_proto}:${dest_ip}:${dest_port}${proxy_arg}"
		procd_set_param respawn
		procd_set_param stdout 1
		procd_set_param stderr 1
		procd_close_instance
	fi

	[ "$firewall_accept" = "1" ] && echo "$listen_port" >> "$PORT_FILE"
}

start_service() {
	local global_enable
	config_load "$CONFIG"
	config_get global_enable "@global[0]" enable
	[ "$global_enable" = "0" ] && return

	mkdir -p "$CONFIG_PATH"
	rm -f "$PORT_FILE"

	config_foreach run_service "config"

	add_rule
}

service_triggers() {
	procd_add_reload_trigger "$CONFIG"
}

stop_service() {
	uci -q delete firewall.socat
	uci commit firewall
	/etc/init.d/firewall reload >/dev/null 2>&1
	rm -rf "$CONFIG_PATH" "$PORT_FILE"
}